[Issue #3] error TS2307: Cannot find module 'handler-function' or its corresponding type declarations
Replaced import which was causing this exception